#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9
repo_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
private_dir=/home/vpsdash/.config/vpsdash
config_file="$private_dir/config.json"
ENV_FILE="$private_dir/smtp.env"
repo=heliowap/vpsdash

if (( EUID != 0 )) || [[ ! -t 0 || ! -t 1 ]]; then
  echo 'Execute em um terminal interativo com sudo: sudo scripts/setup-wizard.sh' >&2
  exit 1
fi
if [[ "${SUDO_USER:-helio}" != helio ]]; then
  echo 'Execute a partir da conta helio; ela guarda a sessão gh e abre o navegador.' >&2
  exit 1
fi
umask 077
cd "$repo_dir"
for required in python3 jq tailscale ssh-keyscan ssh-keygen curl ss; do
  command -v "$required" >/dev/null || { echo "Comando ausente: $required" >&2; exit 1; }
done
operator_path="$PATH"
run_as_operator() {
  runuser -u helio -- env -u GH_TOKEN -u GITHUB_TOKEN \
    HOME=/home/helio PATH="$operator_path" "$@"
}
run_as_service() { runuser -u vpsdash -- env HOME=/home/vpsdash "$@"; }
go_bin="$(run_as_operator bash -lc 'command -v go' || true)"
npm_bin="$(run_as_operator bash -lc 'command -v npm' || true)"
gh_bin="$(run_as_operator bash -lc 'command -v gh' || true)"
node_bin="$(run_as_operator bash -lc 'command -v node' || true)"
if [[ -z "$go_bin" || -z "$npm_bin" || -z "$gh_bin" || -z "$node_bin" ]]; then
  echo 'Go, Node, npm e gh precisam estar disponíveis para helio.' >&2
  exit 1
fi
operator_path="$(dirname -- "$node_bin"):$operator_path"
if ! run_as_operator node -e 'const [major, minor] = process.versions.node.split(".").map(Number); process.exit(major > 22 || (major === 22 && minor >= 12) ? 0 : 1)'; then
  echo 'O build requer Node 22.12 ou posterior; confira a instalação de helio.' >&2
  exit 1
fi
user_systemctl() {
  local uid
  uid="$(id -u vpsdash)"
  run_as_service env XDG_RUNTIME_DIR="/run/user/$uid" \
    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" systemctl --user "$@"
}
pending() { SKIPPED+=("$1"); warn "$1"; }
wizard_error() { printf '  %s✗%s %s\n' "$RED" "$RESET" "$1" >&2; }

# Keep real tailnet names only in the service account's private inventory.
sync_inventory() {
  python3 - "$config_file" <<'PY'
import json
import os
import pathlib
import pwd
import subprocess
import sys
import tempfile

path = pathlib.Path(sys.argv[1])
config = json.loads(path.read_text())
status = json.loads(subprocess.check_output(["tailscale", "status", "--json"]))
devices = [status["Self"], *status.get("Peer", {}).values()]
local_host_id = status["Self"]["DNSName"].split(".")[0]
dns = {device.get("DNSName", "").split(".")[0]: device.get("DNSName", "").rstrip(".")
       for device in devices if device.get("DNSName")}
if not any(host["id"] == local_host_id for host in config["hosts"]):
    # vpsdash cannot read helio's sessions directly; the local collector uses
    # the same restricted SSH bridge verified earlier in this stage.
    config["hosts"].append({
        "id": local_host_id,
        "tailnet_name": status["Self"]["DNSName"].rstrip("."),
        "kind": "vps",
        "ssh_user": "helio",
        "ssh_key_file": "/home/vpsdash/.ssh/id_ed25519_" + local_host_id,
    })
for host in config["hosts"]:
    name = dns.get(host["id"])
    if not name:
        raise SystemExit("Host ausente da tailnet: " + host["id"])
    sample_name = host["tailnet_name"].endswith(".example.invalid")
    host["tailnet_name"] = name
    if host["id"] != local_host_id and host["kind"] == "vps":
        if sample_name or not pathlib.Path(host.get("ssh_key_file", "")).is_file():
            host["kind"] = "presence"
            host.pop("ssh_user", None)
            # Keep the planned key path so another wizard run can offer SSH setup.
config["tailscale_serve_host"] = status["Self"]["DNSName"].rstrip(".")
# The public Caddy route must overwrite X-Real-IP and X-Forwarded-For (README).
# Serve supplies its own X-Forwarded-For, which the login handler reads first.
config.setdefault("trust_proxy_header", True)
owner = pwd.getpwnam("vpsdash")
with tempfile.NamedTemporaryFile("w", dir=path.parent, delete=False) as output:
    json.dump(config, output, indent=2)
    output.write("\n")
    os.fchmod(output.fileno(), 0o600)
    os.fchown(output.fileno(), owner.pw_uid, owner.pw_gid)
os.replace(output.name, path)
PY
}

remote_configured() {
  python3 - "$config_file" "$1" <<'PY'
import json, pathlib, sys
config = json.load(open(sys.argv[1]))
host = next((h for h in config["hosts"] if h["id"] == sys.argv[2]), None)
sys.exit(0 if host and host["kind"] == "vps" and pathlib.Path(host.get("ssh_key_file", "")).is_file() else 1)
PY
}

activate_remote() {
  python3 - "$config_file" "$1" "$2" <<'PY'
import json
import os
import pathlib
import pwd
import sys
import tempfile

path, host_id, ssh_user = pathlib.Path(sys.argv[1]), sys.argv[2], sys.argv[3]
config = json.loads(path.read_text())
host = next(h for h in config["hosts"] if h["id"] == host_id)
host.update(kind="vps", ssh_user=ssh_user,
            ssh_key_file="/home/vpsdash/.ssh/id_ed25519_" + host_id)
owner = pwd.getpwnam("vpsdash")
with tempfile.NamedTemporaryFile("w", dir=path.parent, delete=False) as output:
    json.dump(config, output, indent=2)
    output.write("\n")
    os.fchmod(output.fileno(), 0o600)
    os.fchown(output.fileno(), owner.pw_uid, owner.pw_gid)
os.replace(output.name, path)
PY
}

banner "Configurar vpsdash na VPS"

stage "Instalar serviço"
say "Compila a interface e o binário; instala a conta, a unit e o inventário privado."
if ! confirm "Executar o build e a instalação agora?"; then
  wizard_error 'Instalação não autorizada; execute novamente quando estiver pronto.'
  exit 1
fi
run_as_operator "$npm_bin" --prefix "$repo_dir/web" ci
run_as_operator "$npm_bin" --prefix "$repo_dir/web" run build
run_as_operator "$go_bin" build -trimpath -o "$repo_dir/bin/vpsdash" ./cmd/vpsdash
"$repo_dir/scripts/install-service.sh" "$repo_dir/bin/vpsdash"
say "Serviço instalado; ainda não foi iniciado."
pause

stage "Senha do painel"
if [[ -s "$private_dir/auth.env" ]]; then
  say "auth.env já existe; a senha atual foi preservada."
else
  step "Digite a senha do painel duas vezes; a entrada fica oculta."
  step "O binário grava somente o hash Argon2 e uma chave de sessão em auth.env (0600)."
  run_as_service /home/vpsdash/bin/vpsdash init-auth
fi
pause

stage "Coletores locais"
say "Instala chaves separadas e comandos SSH restritos para helio e gh-agents."
local_host_id="$(tailscale status --json | python3 -c 'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].split(".")[0])')"
mapfile -t planned_remote_hosts < <(jq -r --arg local "$local_host_id" --slurpfile sample "$repo_dir/config.example.json" '
  ($sample[0].hosts | map(select(.kind == "vps" or (.ssh_key_file // "") != "") | .id)) as $sample_vps
  | .hosts[]
  | select(.id != $local and (.kind == "vps" or (.ssh_key_file // "") != "" or (.id as $id | $sample_vps | index($id))))
  | .id
' "$config_file")
# File reading is opt-in. config.example.json has no file_roots, so roots exist
# only when the operator added them to the private inventory; even then the
# bridge roots file is written only after an explicit yes (default no) to a
# prompt listing the exact paths. Declining passes no roots, so the collector
# script leaves any existing roots file untouched.
approved_file_roots=()
approve_file_roots() {
  local host_id="$1" root
  local -a roots
  approved_file_roots=()
  mapfile -t roots < <(jq -r --arg id "$host_id" '.hosts[] | select(.id == $id) | .file_roots[]?' "$config_file")
  (( ${#roots[@]} )) || return 0
  say "O inventário define file_roots para $host_id:"
  for root in "${roots[@]}"; do say "  $root"; done
  if confirm "Autorizar a leitura somente dessas pastas em $host_id?"; then
    approved_file_roots=("${roots[@]}")
  else
    pending "Leitura de arquivos em $host_id não autorizada; o arquivo de raízes não foi alterado."
  fi
}
approve_file_roots "$local_host_id"
"$repo_dir/scripts/setup-local-collector.sh" "${approved_file_roots[@]}"
if getent passwd gh-agents >/dev/null; then
  "$repo_dir/scripts/setup-runner-collector.sh"
else
  pending "Conta gh-agents ausente; configurar o coletor de runners depois."
fi
sync_inventory
pause

stage "Demais VPSs da tailnet"
say "Cada VPS terá uma chave própria. Confira a host key pelo console desse servidor."
for host_id in "${planned_remote_hosts[@]}"; do
  if remote_configured "$host_id"; then
    say "$host_id já está ativo no inventário."
    continue
  fi
  step "Abra o console de $host_id no provedor, ou uma sessão SSH já verificada."
  step "Nesse host, rode: ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub -E sha256"
  note "O valor procurado começa com SHA256:. Enter no campo abaixo pula este host."
  if ! confirm "Configurar a coleta SSH de $host_id agora?"; then
    pending "$host_id ficará com presença Tailscale até configurar a coleta SSH."
    continue
  fi
  while true; do
    ask HOST_FINGERPRINT "Fingerprint de $host_id (ou Enter para pular):"
    if [[ -z "$HOST_FINGERPRINT" ]]; then
      pending "$host_id ficará com presença Tailscale até obter o fingerprint no host remoto."
      break
    fi
    if [[ "$HOST_FINGERPRINT" =~ SHA256:[A-Za-z0-9+/=]+ ]]; then
      HOST_FINGERPRINT="${BASH_REMATCH[0]}"
      break
    fi
    warn "Cole o trecho SHA256:... exibido pelo ssh-keygen no host remoto."
  done
  if [[ -z "$HOST_FINGERPRINT" ]]; then
    unset HOST_FINGERPRINT
    continue
  fi
  ask REMOTE_USER "Usuário SSH de $host_id:"
  approve_file_roots "$host_id"
  "$repo_dir/scripts/setup-remote-collector.sh" "$host_id" "$REMOTE_USER" "$HOST_FINGERPRINT" "${approved_file_roots[@]}"
  activate_remote "$host_id" "$REMOTE_USER"
  unset REMOTE_USER HOST_FINGERPRINT
done
pause

stage "GitHub Actions"
say "O workflow usa OPENCODE_API_KEY, AGENT_RUNNER e CI_RUNNER."
for variable in AGENT_RUNNER CI_RUNNER; do
  if run_as_operator "$gh_bin" variable list --repo "$repo" --json name | \
    jq -e --arg name "$variable" '.[] | select(.name == $name)' >/dev/null; then
    say "$variable já existe; valor preservado."
  else
    run_as_operator "$gh_bin" variable set "$variable" --repo "$repo" --body ubuntu-latest
    say "$variable foi definido como ubuntu-latest."
  fi
done
if run_as_operator "$gh_bin" secret list --repo "$repo" --json name | jq -e '.[] | select(.name == "OPENCODE_API_KEY")' >/dev/null; then
  say "OPENCODE_API_KEY já existe no GitHub; foi preservado."
else
  open_url "https://opencode.ai/auth"
  step "Entre na conta OpenCode Go, copie a API key da página de autenticação."
  ask_secret OPENCODE_API_KEY "Cole a API key (entrada oculta):"
  if [[ -z "$OPENCODE_API_KEY" ]]; then
    pending "OPENCODE_API_KEY continua ausente."
  elif confirm "Gravar OPENCODE_API_KEY como secret do repositório $repo?"; then
    printf '%s' "$OPENCODE_API_KEY" | run_as_operator "$gh_bin" secret set OPENCODE_API_KEY --repo "$repo"
    WRITTEN_SECRET+=(OPENCODE_API_KEY)
    say "Secret gravado; o valor não foi salvo na VPS."
  else
    pending "OPENCODE_API_KEY continua ausente."
  fi
  unset OPENCODE_API_KEY
fi
pause

stage "Registrar GitHub App"
if [[ -s "$private_dir/github-app.env" && -s "$private_dir/github-app.pem" ]]; then
  say "Credenciais do App já existem; o código de uso único não será solicitado."
elif ! confirm "Registrar o GitHub App no navegador agora?"; then
  pending "GitHub App ainda não foi registrado."
else
  say "O manifesto solicita apenas as permissões descritas em app-manifest.json."
  form_file="$(mktemp /tmp/vpsdash-app-form.XXXXXX.html)"
  run_as_operator python3 "$repo_dir/scripts/manifest-form.py" > "$form_file"
  chown helio:helio "$form_file"
  chmod 600 "$form_file"
  step "Abra $form_file no navegador de helio e clique em Continuar no GitHub."
  open_url "file://$form_file"
  self_dns="$(tailscale status --json | python3 -c 'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))')"
  step "Se estiver conectado por SSH, copie o arquivo para o seu computador: scp helio@$self_dns:$form_file ./vpsdash-app-form.html"
  step "Revise as permissões, crie o App na conta heliowap e copie o parâmetro code da URL de retorno."
  say "O código expira em uma hora e será lido sem eco nem argumento de processo."
  ask_secret APP_CODE "Código de uso único:"
  if [[ -n "$APP_CODE" ]]; then
    printf '%s\n' "$APP_CODE" | "$repo_dir/scripts/convert-app-manifest.sh"
  else
    pending "GitHub App ainda não foi registrado."
  fi
  unset APP_CODE
  rm -f "$form_file"
fi
pause

stage "Instalar GitHub App"
if [[ ! -s "$private_dir/github-app.env" ]]; then
  pending "Instalação do GitHub App aguarda o registro do App."
else
  current_installation="$(python3 - "$private_dir/github-app.env" <<'PY'
import json, pathlib, sys
values = dict(line.split("=", 1) for line in pathlib.Path(sys.argv[1]).read_text().splitlines() if "=" in line)
print(json.loads(values.get("GITHUB_INSTALLATIONS_JSON", "{}")).get("heliowap", ""))
PY
)"
  if [[ "$current_installation" =~ ^[1-9][0-9]*$ ]]; then
    say "A instalação heliowap já está registrada; ID preservado."
  elif ! confirm "Instalar o App na conta heliowap agora?"; then
    pending "GitHub App ainda não foi instalado em heliowap."
  else
    ask APP_SLUG "Slug do App no GitHub [gh-agents-ops]:"
    APP_SLUG="${APP_SLUG:-gh-agents-ops}"
    if [[ ! "$APP_SLUG" =~ ^[A-Za-z0-9-]+$ ]]; then
      echo 'Slug do App inválido.' >&2
      exit 1
    fi
    open_url "https://github.com/apps/$APP_SLUG/installations/new"
    step "Selecione heliowap, inclua o repositório vpsdash e clique em Install."
    step "Abra Settings → Applications → Installed GitHub Apps → Configure; copie o número final da URL."
    ask INSTALL_ID "Installation ID numérico de heliowap:"
    if [[ ! "$INSTALL_ID" =~ ^[1-9][0-9]*$ ]]; then
      echo 'Installation ID inválido.' >&2
      exit 1
    fi
    ENV_FILE="$private_dir/github-app.env"
    write_env GITHUB_INSTALLATIONS_JSON "{\"heliowap\":$INSTALL_ID}"
    chown vpsdash:vpsdash "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    ENV_FILE="$private_dir/smtp.env"
    unset APP_SLUG INSTALL_ID
  fi
fi
pause

stage "Canal SMTP"
say "Crie uma conta de envio no servidor de e-mail e confirme porta e autenticação."
if [[ -s "$private_dir/smtp.env" ]] && ! confirm "Revisar as credenciais SMTP existentes?"; then
  say "smtp.env existente foi preservado."
elif ! confirm "A conta SMTP está pronta para configurar agora?"; then
  pending "Canal SMTP segue sem configuração; alertas permanecem na fila."
else
  SMTP_HOST=""
  ask SMTP_HOST "Nome DNS com certificado TLS válido do servidor SMTP:"
  ask SMTP_PORT "Porta SMTP [587; ou 465 para TLS implícito]:"
  SMTP_PORT="${SMTP_PORT:-587}"
  if [[ ! "$SMTP_HOST" =~ ^[A-Za-z0-9.-]+$ ]] || [[ "$SMTP_PORT" != 587 && "$SMTP_PORT" != 465 ]]; then
    echo 'Host ou porta SMTP inválido.' >&2
    exit 1
  fi
  if ! python3 - "$SMTP_HOST" "$SMTP_PORT" <<'PY'
import socket, sys
try:
    with socket.create_connection((sys.argv[1], int(sys.argv[2])), timeout=8):
        pass
except OSError:
    raise SystemExit("Porta SMTP indisponível")
PY
  then
    pending "SMTP indisponível; confira serviço/firewall e execute o assistente novamente."
  else
    ask SMTP_USER "Conta de envio SMTP:"
    ask SMTP_TO "Destinatário dos alertas:"
    ask SMTP_AUTH "Autenticação [plain ou login]:"
    SMTP_AUTH="${SMTP_AUTH:-plain}"
    if [[ "$SMTP_AUTH" != plain && "$SMTP_AUTH" != login ]]; then
      echo 'SMTP_AUTH deve ser plain ou login.' >&2
      exit 1
    fi
    ask_secret SMTP_PASSWORD "Senha da conta SMTP (entrada oculta):"
    if [[ -z "$SMTP_USER" || -z "$SMTP_TO" || -z "$SMTP_PASSWORD" ||
          "$SMTP_PASSWORD" == [\"\']* || "$SMTP_PASSWORD" == *[\"\'] ]]; then
      echo 'Credenciais SMTP incompletas ou senha com aspas nas bordas.' >&2
      exit 1
    fi
    if printf '%s' "$SMTP_PASSWORD" | python3 -c '
import smtplib, ssl, sys
host, port, user, mechanism = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]
password = sys.stdin.read()
try:
    if port == 465:
        smtp = smtplib.SMTP_SSL(host, port, timeout=10, context=ssl.create_default_context())
    else:
        smtp = smtplib.SMTP(host, port, timeout=10)
        smtp.starttls(context=ssl.create_default_context())
    with smtp:
        smtp.ehlo()
        if mechanism.upper() not in smtp.esmtp_features.get("auth", "").upper().split():
            raise ValueError("Mecanismo AUTH não anunciado pelo servidor")
        smtp.user, smtp.password = user, password
        smtp.auth(mechanism.upper(), smtp.auth_plain if mechanism == "plain" else smtp.auth_login,
                  initial_response_ok=True)
except Exception as error:
    raise SystemExit("Falha no teste SMTP/TLS/AUTH: " + type(error).__name__)
' "$SMTP_HOST" "$SMTP_PORT" "$SMTP_USER" "$SMTP_AUTH"; then
      write_env SMTP_HOST "$SMTP_HOST"
      write_env SMTP_PORT "$SMTP_PORT"
      write_env SMTP_USER "$SMTP_USER"
      write_env SMTP_PASSWORD "$SMTP_PASSWORD"
      write_env SMTP_TO "$SMTP_TO"
      write_env SMTP_AUTH "$SMTP_AUTH"
      chown vpsdash:vpsdash "$ENV_FILE"
      chmod 600 "$ENV_FILE"
      say "SMTP autenticado e salvo em arquivo privado."
    else
      pending "SMTP não autenticou; nenhuma credencial nova foi gravada."
    fi
    unset SMTP_USER SMTP_TO SMTP_AUTH SMTP_PASSWORD
  fi
  unset SMTP_HOST SMTP_PORT
fi
pause

stage "Iniciar e publicar na tailnet"
if ! run_as_service /home/vpsdash/bin/vpsdash check-config --config "$config_file"; then
  wizard_error "Inventário inválido em $config_file; corrija-o antes de iniciar o serviço."
  exit 1
fi
user_systemctl daemon-reload
user_systemctl enable vpsdash.service
user_systemctl restart vpsdash.service
user_systemctl is-active --quiet vpsdash.service
listen_addr="$(jq -er '.listen | strings' "$config_file")"
health_url="http://$listen_addr/healthz"
for ((attempt=0; attempt<10; attempt++)); do
  if curl -fsS --max-time 2 "$health_url" -o /dev/null 2>/dev/null; then
    break
  fi
  sleep 1
done
curl -fsS --max-time 5 "$health_url" -o /dev/null
if tailscale serve status --json | jq -e '(.AllowFunnel // {}) | any(.[])' >/dev/null; then
  wizard_error 'Tailscale Funnel está ativo neste host; revise antes de publicar o painel.'
  exit 1
fi
self_dns="$(tailscale status --json | python3 -c 'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))')"
panel_serve_port() {
  tailscale serve status --json | jq -r --arg dns "$self_dns" --arg backend "http://$listen_addr" '
    [ . as $status
      | (.Web // {}) | to_entries[]
      | select(.key | startswith($dns + ":"))
      | select(.value.Handlers["/"].Proxy == $backend)
      | .key | split(":")[-1]
      | select($status.TCP[.].HTTPS == true)
    ] | .[0] // empty'
}
say "O serviço respondeu em loopback. Estado atual do Tailscale Serve:"
tailscale serve status
serve_port="$(panel_serve_port)"
if [[ -n "$serve_port" ]]; then
  say "Serve já encaminha HTTPS na porta $serve_port para o painel."
elif confirm "Publicar o painel com Tailscale Serve HTTPS privado?"; then
  serve_port=443
  if ss -Hlt '( sport = :443 )' | grep -q .; then
    serve_port=8443
    say "A porta 443 está ocupada; Serve usará a porta 8443."
  fi
  if ss -Hlt "( sport = :$serve_port )" | grep -q .; then
    wizard_error "A porta $serve_port também está ocupada; libere-a antes de publicar o painel."
    exit 1
  fi
  tailscale serve --https="$serve_port" --bg "$listen_addr"
  serve_port="$(panel_serve_port)"
  if [[ -z "$serve_port" ]]; then
    wizard_error 'Serve não registrou a rota HTTPS para o painel.'
    exit 1
  fi
else
  pending "Tailscale Serve ainda não publica o painel."
fi
if [[ -n "$serve_port" ]]; then
  panel_url="https://$self_dns"
  if [[ "$serve_port" != 443 ]]; then
    panel_url+=":$serve_port"
  fi
  say "Verificando $panel_url; o primeiro certificado pode levar alguns minutos."
  for ((attempt=0; attempt<18; attempt++)); do
    if curl -fsS --max-time 5 "$panel_url/healthz" -o /dev/null 2>/dev/null; then
      break
    fi
    sleep 5
  done
  curl -fsS --max-time 15 "$panel_url/healthz" -o /dev/null
  open_url "$panel_url"
  if ! confirm "Conseguiu entrar no painel pelo navegador da tailnet?"; then
    pending "Confirmar login no navegador da tailnet."
  fi
fi
ENV_FILE="$private_dir"
finish
if (( ${#SKIPPED[@]} )); then
  wizard_error 'Configuração parcial. Execute o assistente novamente após resolver as pendências.'
  exit 2
fi
