export type Metric = { ts: number; cpu_pct?: number; mem_pct: number; disk_pct: number; uptime_s: number }
export type Host = { id: string; tailnet_name: string; kind: 'vps' | 'presence'; ssh_user?: string; online: boolean; seen_at?: number; latest?: Metric }
export type Project = { id: number; host_id: string; name: string; source: 'docker' | 'systemd' | 'tmux'; monitored: boolean; native?: boolean; health_url?: string; expected?: string; check_ok?: boolean; check_planned?: boolean; checked_at?: number }
export type Runner = { repo: string; runner_id: number; name: string; status: string; busy: boolean; job?: string; seen_at: number }
export type Session = { host_id: string; name: string; pane_pid: number; cwd: string; agent?: string; state?: string; seen_at: number }
export type Run = { id: number; name: string; display_title: string; html_url: string; status: string; conclusion?: string }
export type Repository = { name: string; agent_switchable: boolean; ci_switchable: boolean; agent_runner: string; ci_runner: string; agent_known: boolean; ci_known: boolean; agent_error?: string; ci_error?: string; error?: string }
export type ProjectIncident = { source: 'checks' | 'alert'; state: 'open' | 'recovered' | 'unresolved'; started_at: number; start_known: boolean; last_failure_at?: number; recovered_at?: number; failed_checks: number; detail: string; alert_at?: number }
export type IncidentHistory = { project_id: number; monitored: boolean; observed_at: number; checks_since: number; alerts_since: number; alert_threshold: number; check_count: number; first_check_at?: number; last_check_at?: number; truncated: boolean; incidents: ProjectIncident[] }
export type Dashboard = { hosts: Host[]; projects: Project[]; runners: Runner[]; sessions: Session[]; queued: Record<string, Run[]>; repositories: Repository[]; collector_errors: Record<string, string>; fleet_seen_at: number; smtp_provisioned: boolean; unit_ops?: UnitOp[]; file_roots?: Record<string, string[]>; private: boolean }
export type BackendUsage = { backend: string; jobs_7d: number; minutes_7d: number; jobs_30d: number; minutes_30d: number }
export type RepoMinutes = { repo: string; collected_at: number; covered_since: number; attempted_at: number; error?: string; backends: BackendUsage[] }
export type MinutesReport = { generated_at: number; collector_enabled: boolean; interval_s: number; repositories: RepoMinutes[] }
export type Job = { repo: string; id: number; run_id: number; name: string; workflow?: string; run_title?: string; status: string; conclusion?: string; runner_name?: string; started_at?: number; completed_at?: number; html_url?: string }
export type JobList = { jobs: Job[]; errors: Record<string, string>; observed_at: number }
export type JobLog = { job: Job; log: { state: 'ok' | 'pending' | 'unavailable' | 'expired' | 'too_large'; text: string; size: number; truncated: boolean; message?: string }; complete: boolean; poll_after_ms: number; observed_at: number }
export type UnitOp = { id: number; host_id: string; unit: string; action: 'restart' | 'drain'; status: 'running' | 'done' | 'failed' | 'cancelled' | 'expired'; detail?: string; requested_at: number; finished_at?: number; stop_unconfirmed?: boolean }
export type FileEntry = { name: string; type: 'dir' | 'file' | 'other'; size: number; mtime: number; link: boolean; blocked: boolean; reason: string }
export type FileListing = { path: string; entries: FileEntry[]; truncated: boolean }
export type FileContent = { path: string; size: number; mtime: number; offset: number; length: number; next_offset: number; truncated: boolean; binary: boolean; content: string }
export type Snippet = { name: string; argv: string[]; timeout_seconds: number }
export type InteractiveHost = { id: string; terminal: boolean; key_missing?: boolean; local_command: string; attach_commands: Record<string, string>; snippets: Snippet[] }
export type InteractiveInfo = { hosts: InteractiveHost[]; step_up_until: number; active: number; max_sessions: number; idle_minutes: number }
export type AuditEntry = { id: number; ts: number; action: 'step_up' | 'terminal' | 'attach_ro' | 'attach_rw' | 'snippet' | 'send_keys'; host_id: string; target: string; client_ip: string; outcome: 'ok' | 'denied' | 'failed' | 'closed' }
export type SnippetResult = { name: string; duration_ms: number; result: { output: string; truncated: boolean; exit_code: number; timed_out: boolean } }
export type TerminalRequest = { host: string; kind: 'terminal' | 'attach'; session?: string; write?: boolean; confirm_write?: boolean }
export type ReplyKey = 'Enter' | 'Escape' | 'Up' | 'Down' | 'Tab' | 'y' | 'n' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
export type Reply = { key: ReplyKey } | { text: string; enter: boolean }
export type SessionFocus = { host: string; session: string }
